//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace takionline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Firma
    {
        public int Id { get; set; }
        public string FirmaAdi { get; set; }
        public string Stok { get; set; }
        public string FirmaTel { get; set; }
        public string FirmaAdres { get; set; }
        public string FirmaMail { get; set; }
        public string FirmaSehir { get; set; }
    }
}
